Notify client when tool list changed (#152)
* Initial tool list change implementationc

* Add unit test for tool addition

* Add unit test for tool removal

* Fix error TS2441: Duplicate identifier 'require'. Compiler reserves name 'require' in top level scope of a module.

* Add unit test for tools not changed

* Add unit test for tool schema changed

* Remove jest timeout used for debugging purpose

* Introduce config object to simplify createTestEnvironment signature

* Introduce config object to simplify setupNockMocks  signature

* Use port 0 to let the OS assign a random available port

* Wait for the server to be listening before accessing the address

* Fix test setup: Ensure nock interceptors are always persisted for polling tests

* Add proper nock cleanup for polling tests

* Remove Bob' signature on tests ;-)

* Use pollTimeoutFactor constant and increase its value to stabilize polling tests

* Fix duplicate registration bug for new tool in multi-operation decision OpenAPi specification

* Address  JeanFi's concerns

* Use more meaningful name for isPersistingNockScope

* Remove redundant nock.cleanAll() call

* Fix inconsitent spacing in README table column

* Environment variable constants, option resolution helper and Commander program setup

* Use environment variable constants (continued)

* Use option resolver (continued), decouple internal poll interval in ms

* Simplify code: SDK is already sending tool list changed when adding/removing/updating a tool

* Remove duplicate execution callback definition

* Fix linting

* Refactor checkForToolChanges

* Fix race condition while polling for tool change

* Refactor tool change mechanism

* Renamed EnvironmentVariables constant

* Simplify flow

* Now polling for tool changes whatever the transport type

* Increase poll interval for polling test

* Fix typo in comment

* Fix copy/paste erro for POLL_INTERVAL